# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_vertex <- function(merge_mat, i) {
    .Call(`_VisualStock_create_vertex`, merge_mat, i)
}

rcpp_hello_world <- function() {
    .Call(`_VisualStock_rcpp_hello_world`)
}

